apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service


#  # kv format
#  key: "value"
#  $actual-config-file$: "name.properties"
#
#  # file format
#  name.properties: |
#    field=value1,value2
