const famousCodingBooks1 = [
    { bookName: "Clean Code", authorName: "Robert C. Martin" },
    { bookName: "The Pragmatic Programmer", authorName: "Andrew Hunt and David Thomas" },
    { bookName: "You Don't Know JS", authorName: "Kyle Simpson" },
    { bookName: "JavaScript: The Good Parts", authorName: "Douglas Crockford" },
    { bookName: "Eloquent JavaScript", authorName: "Marijn Haverbeke" },
    { bookName: "Learning Python", authorName: "Mark Lutz" },
    { bookName: "Design Patterns", authorName: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides" },
    { bookName: "The Art of Computer Programming", authorName: "Donald Knuth" },
    { bookName: "Introduction to the Theory of Computation", authorName: "Michael Sipser" },
    { bookName: "Cracking the Coding Interview", authorName: "Gayle Laakmann McDowell" },
    { bookName: "Artificial Intelligence: A Modern Approach", authorName: "Stuart Russell and Peter Norvig" },
    { bookName: "Code Complete", authorName: "Steve McConnell" },
    { bookName: "The Mythical Man-Month", authorName: "Frederick P. Brooks Jr." },
    { bookName: "The Pragmatic Programmer", authorName: "Andrew Hunt and David Thomas" },
    { bookName: "Structure and Interpretation of Computer Programs", authorName: "Abraham Silberschatz, Peter B. Galvin, and Greg Gagne" },
    { bookName: "Computer Networking: A Top-Down Approach", authorName: "James Kurose and Keith Ross" },
    { bookName: "Introduction to Algorithms", authorName: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein" },
    { bookName: "JavaScript: The Definitive Guide", authorName: "David Flanagan" },
    { bookName: "The Complete Reference C", authorName: "Herbert Schildt" },
    { bookName: "Head First Design Patterns", authorName: "Eric Freeman and Bert Bates" },
    { bookName: "Python Crash Course", authorName: "Eric Matthes" },
    { bookName: "The Phoenix Project", authorName: "Gene Kim, Kevin Behr, and George Spafford" },
    { bookName: "Continuous Delivery", authorName: "Jez Humble and David Farley" },
    { bookName: "Refactoring: Improving the Design of Existing Code", authorName: "Martin Fowler" },
    { bookName: "Effective Java", authorName: "Joshua Bloch" },
    { bookName: "The Clean Coder", authorName: "Robert C. Martin" },
    { bookName: "Python for Data Analysis", authorName: "Wes McKinney" },
    { bookName: "Artificial Intelligence for Humans", authorName: "Jeff Heaton" },
    { bookName: "Software Engineering at Google", authorName: "Titus Winters, Tom Manshreck, and Hyrum Wright" },
    { bookName: "Grokking Algorithms", authorName: "Aditya Bhargava" },
    { bookName: "Deep Learning", authorName: "Ian Goodfellow, Yoshua Bengio, and Aaron Courville" },
    { bookName: "Programming in Haskell", authorName: "Paul Hudak" },
    { bookName: "Learning Java", authorName: "Brett McLaughlin, Gary Palgon, and David Flanagan" },
    { bookName: "C Programming Language", authorName: "Brian W. Kernighan and Dennis M. Ritchie" },
    { bookName: "C# in Depth", authorName: "Jon Skeet" },
    { bookName: "The Lean Startup", authorName: "Eric Ries" },
    { bookName: "Machine Learning Yearning", authorName: "Andrew Ng" },
    { bookName: "Introduction to the Theory of Computation", authorName: "Michael Sipser" },
    { bookName: "Principles of Compiler Design", authorName: "Aho, Lam, Sethi, and Ullman" },
    { bookName: "Modern Operating Systems", authorName: "Andrew S. Tanenbaum" },
    { bookName: "Computer Vision: Algorithms and Applications", authorName: "Richard Szeliski" },
    { bookName: "Game Programming Patterns", authorName: "Robert Nystrom" },
    { bookName: "Designing Data-Intensive Applications", authorName: "Martin Kleppmann" },
    { bookName: "The Complete Software Developer's Career Guide", authorName: "John Sonmez" },
    { bookName: "The Algorithm Design Manual", authorName: "Steven S. Skiena" },
    { bookName: "Operating System Concepts", authorName: "Abraham Silberschatz, Peter B. Galvin, and Greg Gagne" },
    { bookName: "The Elements of Statistical Learning", authorName: "Trevor Hastie, Robert Tibshirani, and Jerome Friedman" },
    { bookName: "Blockchain Basics", authorName: "Daniel Drescher" },
    { bookName: "Data Structures and Algorithms Made Easy", authorName: "Narasimha Karumanchi" },
    { bookName: "Introduction to Algorithms", authorName: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, and Clifford Stein" },
    { bookName: "Algorithms", authorName: "Robert Sedgewick and Kevin Wayne" },
    { bookName: "The Algorithm Design Manual", authorName: "Steven S. Skiena" },
    { bookName: "Cracking the Coding Interview", authorName: "Gayle Laakmann McDowell" },
    { bookName: "Data Structures and Algorithms in Java", authorName: "Robert Lafore" },
    { bookName: "Data Structures and Algorithm Analysis in C++", authorName: "Mark Allen Weiss" },
    { bookName: "Grokking Algorithms", authorName: "Aditya Bhargava" },
    { bookName: "Algorithms Unlocked", authorName: "Thomas H. Cormen" },
    { bookName: "Elements of Programming Interviews", authorName: "Adnan Aziz, Tsung-Hsien Lee, and Amit Prakash" },
    { bookName: "Algorithm Design", authorName: "Jon Kleinberg and Éva Tardos" },
    { bookName: "Data Structures for Interviews", authorName: "Meenakshi" },
    { bookName: "Algorithms in a Nutshell", authorName: "George T. Heineman, Gary Pollice, and Stanley Selkow" },
    { bookName: "Introduction to Data Structures and Algorithms with Python", authorName: "Rance D. Necaise" },
    { bookName: "Data Structures and Algorithms in Python", authorName: "Michael T. Goodrich, Roberto Tamassia, and Michael H. Goldwasser" },
    { bookName: "Algorithms for Interviews", authorName: "Adnan Aziz, Amit Prakash, and Tsung-Hsien Lee" },
    { bookName: "Programming Pearls", authorName: "Jon Bentley" },
    { bookName: "Data Structures and Algorithms: A Comprehensive Guide", authorName: "Ranjeet Nair" },
    { bookName: "Data Structures and Algorithms in JavaScript", authorName: "Michael McMillan" },
    { bookName: "Data Structures and Algorithms in C#", authorName: "Michael McMillan" },
    { bookName: "Designing Data-Intensive Applications", authorName: "Martin Kleppmann" },
    { bookName: "System Design Interview – An Insider's Guide", authorName: "Alex Xu" },
    { bookName: "Designing Microservices", authorName: "O'Reilly Media" },
    { bookName: "Microservices Patterns: With Examples in Java", authorName: "Chris Richardson" },
    { bookName: "Site Reliability Engineering: How Google Runs Production Systems", authorName: "Niall Richard Murphy, Betsy Beyer, Chris Jones, and Jennifer Petoff" },
    { bookName: "The Art of Scalability", authorName: "Martin L. Abbott and Michael T. Fisher" },
    { bookName: "Building Microservices", authorName: "Sam Newman" },
    { bookName: "Software Architecture Patterns", authorName: "Mark Richards" },
    { bookName: "Clean Architecture: A Craftsman's Guide to Software Structure and Design", authorName: "Robert C. Martin" },
    { bookName: "The Phoenix Project", authorName: "Gene Kim, Kevin Behr, and George Spafford" },
    { bookName: "The Lean Startup", authorName: "Eric Ries" },
    { bookName: "Domain-Driven Design: Tackling Complexity in the Heart of Software", authorName: "Eric Evans" },
    { bookName: "Software Engineering at Google", authorName: "Titus Winters, Tom Manshreck, and Hyrum Wright" },
    { bookName: "Release It!: Design and Deploy Production-Ready Software", authorName: "Michael T. Nygard" },
    { bookName: "Building Event-Driven Microservices", authorName: "Adam Bellemare" },
    { bookName: "Kubernetes Up & Running", authorName: "Kelsey Hightower, Brendan Burns, and Joe Beda" },
    { bookName: "Distributed Systems: Principles and Paradigms", authorName: "Andrew S. Tanenbaum and Maarten Van Steen" },
    { bookName: "High-Performance Browser Networking", authorName: "Ilya Grigorik" },
    { bookName: "Fundamentals of Software Architecture", authorName: "Mark Richards and Neal Ford" },
    { bookName: "Architecting for the Cloud", authorName: "Michael J. Kavis" },
    { bookName: "Computer Systems: A Programmer's Perspective", authorName: "Randal E. Bryant and David R. O'Hallaron" },
    { bookName: "Operating Systems: Three Easy Pieces", authorName: "Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau" },
    { bookName: "Modern Operating Systems", authorName: "Andrew S. Tanenbaum" },
    { bookName: "Understanding the Linux Kernel", authorName: "Daniel P. Bovet and Marco Cesati" },
    { bookName: "The Linux Programming Interface", authorName: "Michael Kerrisk" },
    { bookName: "Programming in C", authorName: "Stephen G. Kochan" },
    { bookName: "C Programming: A Modern Approach", authorName: "K. N. King" },
    { bookName: "Computer Networking: A Top-Down Approach", authorName: "James Kurose and Keith Ross" },
    { bookName: "Computer Organization and Design", authorName: "David A. Patterson and John L. Hennessy" },
    { bookName: "Computer Architecture: A Quantitative Approach", authorName: "John L. Hennessy and David A. Patterson" },
    { bookName: "Effective Java", authorName: "Joshua Bloch" },
    { bookName: "Java Concurrency in Practice", authorName: "Brian Goetz" },
    { bookName: "Clean Code: A Handbook of Agile Software Craftsmanship", authorName: "Robert C. Martin" },
    { bookName: "Refactoring: Improving the Design of Existing Code", authorName: "Martin Fowler" },
    { bookName: "The Pragmatic Programmer: Your Journey To Mastery", authorName: "Andrew Hunt and David Thomas" },
    { bookName: "You Don't Know JS", authorName: "Kyle Simpson" },
    { bookName: "Head First Java", authorName: "Kathy Sierra and Bert Bates" },
    { bookName: "Learning Java", authorName: "Marc Loy, Kathy Sierra, and Bert Bates" },
    { bookName: "JavaScript: The Good Parts", authorName: "Douglas Crockford" },
    { bookName: "Fluent Python", authorName: "Luciano Ramalho" },
    { bookName: "Programming in Haskell", authorName: "Graham Hutton" },
    { bookName: "Python Crash Course", authorName: "Eric Matthes" },
    { bookName: "The Ruby Programming Language", authorName: "David Flanagan and Yukihiro Matsumoto" },
    { bookName: "JavaScript: The Definitive Guide", authorName: "David Flanagan" },
    { bookName: "Python Cookbook", authorName: "David Beazley and Brian K. Jones" },
    { bookName: "The Go Programming Language", authorName: "Alan A. A. Donovan and Brian W. Kernighan" },
    { bookName: "Eloquent JavaScript", authorName: "Marijn Haverbeke" },
    { bookName: "C# in Depth", authorName: "Jon Skeet" },
    { bookName: "Programming Rust", authorName: "Jim Blandy and Jason Orendorff" },
    { bookName: "Head First Design Patterns", authorName: "Eric Freeman and Bert Bates" },
    { bookName: "Software Engineering: A Practitioner's Approach", authorName: "Roger S. Pressman" },
    { bookName: "The Mythical Man-Month: Essays on Software Engineering", authorName: "Frederick P. Brooks Jr." },
    { bookName: "Continuous Delivery: Reliable Software Releases through Build, Test, and Deployment Automation", authorName: "Jez Humble and David Farley" },
    { bookName: "Software Estimation: Demystifying the Black Art", authorName: "Steve McConnell" },
    { bookName: "Working Effectively with Legacy Code", authorName: "Michael C. Feathers" },
    { bookName: "The Art of Software Security Assessment", authorName: "Mark Dowd, John McDonald, and Justin Schuh" },
    { bookName: "Lean Software Development: An Agile Toolkit", authorName: "Mary Poppendieck and Tom Poppendieck" },
    { bookName: "The Art of Unit Testing", authorName: "Roy Osherove" },
    { bookName: "The Pragmatic Programmer", authorName: "Andrew Hunt and David Thomas" },
    { bookName: "Domain-Driven Design Distilled", authorName: "Vaughn Vernon" },
    { bookName: "HTML and CSS: Design and Build Websites", authorName: "Jon Duckett" },
    { bookName: "Pattern Recognition and Machine Learning", authorName: "Christopher Bishop" },
    { bookName: "Data Science Handbook", authorName: "Jake VanderPlas" },
    { bookName: "Hacking: The Art of Exploitation", authorName: "Jon Erickson" },
    { bookName: "Java: A Beginner's Guide", authorName: "Herbert Schildt" },
    { bookName: "The Elements of Computing Systems", authorName: "Noam Nisan and Shimon Schocken" },
    { bookName: "Machine Learning", authorName: "Andrew Ng and Michael I. Jordan" },
    { bookName: "Data Mining: Concepts and Techniques", authorName: "Jiawei Han and Micheline Kamber" },
    { bookName: "Web Development and Design Foundations", authorName: "Felke-Morris" },
    { bookName: "The AI Advantage", authorName: "Thomas H. Davenport" },
    { bookName: "Natural Language Processing (almost) from Scratch", authorName: "Collobert et al." },
    { bookName: "Deep Learning for Computer Vision", authorName: "Rajalingappaa Shanmugamani" },
    { bookName: "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", authorName: "Aurélien Géron" },
    { bookName: "R for Data Science", authorName: "Hadley Wickham and Garrett Grolemund" },
    { bookName: "SQL Queries for Mere Mortals", authorName: "John D. Cook" },
    { bookName: "The Web Application Hacker's Handbook", authorName: "Dafydd Stuttard and Marcus Pinto" },
    { bookName: "Network Security Essentials", authorName: "William Stallings" },
    { bookName: "Cryptography and Network Security", authorName: "William Stallings" },
    { bookName: "Compilers: Principles, Techniques, and Tools", authorName: "Alfred Aho, Monica Lam, Ravi Sethi, and Jeffrey Ullman" },
    { bookName: "Database Systems: The Complete Book", authorName: "Hector Garcia-Molina, Ivan Martinez, and Jose Valenza" },
    { bookName: "Natural Language Processing with Python", authorName: "Steven Bird, Ewan Klein, and Edward Loper" },
    { bookName: "Automate the Boring Stuff with Python", authorName: "Al Sweigart" },
    { bookName: "Full Stack Development with Python", authorName: "Apress" },
    { bookName: "Machine Learning with Python", authorName: "William McKinney" },
    { bookName: "Deep Learning with Python", authorName: "Francois Chollet" },
    { bookName: "Python Data Science Handbook", authorName: "Jake VanderPlas" },
    { bookName: "Python Machine Learning", authorName: "Sebastian Raschka" },
    { bookName: "Hands-On Machine Learning with TensorFlow", authorName: "Aurélien Géron" },
    { bookName: "Deep Learning with Keras", authorName: "Antonio Gulli and Sujit Pal" },
    { bookName: "Natural Language Processing with Deep Learning", authorName: "Yoav Goldberg" },
    { bookName: "Computer Networks", authorName: "Andrew S. Tanenbaum and David J. Wetherall" },
    { bookName: "Cybersecurity 101", authorName: "Mark Stanislav" },
    { bookName: "Hacking Exposed", authorName: "Stuart McClure, Joel Scambray, and George Kurtz" },
    { bookName: "The Hacker's Handbook", authorName: " Hugo Cornwall, Steve Gold, and Ben Laurie" },
    { bookName: "Web Application Security Essentials", authorName: "Ofer Shezaf" },
    { bookName: "Data Science for Business", authorName: "Foster Provost and Tom Fawcett" },
    { bookName: "Big Data: The Missing Manual", authorName: "Tim O'Reilly" },
    { bookName: "Data Mining: Practical Machine Learning Tools and Techniques", authorName: "Ian H. Witten, Eibe Frank, and Mark A. Hall" },
    { bookName: "The Data Warehouse Toolkit", authorName: "Ralph Kimball and Margy Ross" },
    { bookName: "Data Visualization: A Handbook for Data Driven Design", authorName: "Andy Kirk" },
    { bookName: "Python Data Analysis", authorName: "Wes McKinney" },
    { bookName: "R for Data Science", authorName: "Hadley Wickham and Garrett Grolemund" },
    { bookName: "SQL Queries for Mere Mortals", authorName: "John D. Cook" },
    { bookName: "The Art of SQL", authorName: "Stephane Faroult" },
    { bookName: "Learning Java", authorName: "Patrick Niemeyer and Daniel Leuck" },
    { bookName: "Java: The Complete Reference", authorName: "Herbert Schildt" },
    { bookName: "Head First Java", authorName: "Kathy Sierra and Bert Bates" },
    { bookName: "Java Performance: The Definitive Guide", authorName: "Scott Oaks" },
    { bookName: "Java Concurrency in Practice", authorName: "Brian Goetz and Tim Peierls" },
    { bookName: "HTML5: The Missing Manual", authorName: "Matthew MacDonald" },
    { bookName: "CSS Pocket Reference", authorName: "Eric A. Meyer" },
    { bookName: "JavaScript Enlightenment", authorName: "Cody Lindley" },
    { bookName: "Eloquent JavaScript", authorName: "Marijn Haverbeke" },
    { bookName: "JavaScript: The Good Parts", authorName: "Douglas Crockford" },
    { bookName: "Node.js in Action", authorName: "Mike Cantelon, Marc Harter, TJ Holowaychuk, and Nathan Rajlich" },
    { bookName: "Full Stack Development with Python", authorName: "Apress" },
    { bookName: "Python Web Development with Flask", authorName: "Miguel Grinberg" },
    { bookName: "Django By Example", authorName: "Antonio Mele" },
    { bookName: "Python Network Programming", authorName: "M. O. Faruque Sarker and Samer Faour" },
    { bookName: "Automate the Boring Stuff with Python", authorName: "Al Sweigart" },
    { bookName: "Invent Your Own Computer Games with Python", authorName: "Al Sweigart" },
    { bookName: "Python Crash Course", authorName: "Eric Matthes" },
    { bookName: "Learning Python", authorName: "Mark Lutz" },
    { bookName: "Python for Data Analysis", authorName: "Wes McKinney" },
    { bookName: "Python Machine Learning", authorName: "Sebastian Raschka" },
    { bookName: "Deep Learning with Python", authorName: "Francois Chollet" },
    { bookName: "Python Data Science Handbook", authorName: "Jake VanderPlas" },
    { bookName: "Python for Everybody", authorName: "Charles Severance" },
    { bookName: "Introduction to Algorithms", authorName: "Thomas H. Cormen" },
    { bookName: "The Algorithm Design Manual", authorName: "Steven S. Skiena" },
    { bookName: "Data Structures and Algorithms in Python", authorName: "Michael T. Goodrich et al." },
    { bookName: "Grokking Algorithms", authorName: "Aditya Bhargava" },
    { bookName: "Algorithms to Live By", authorName: "Brian Christian and Tom Griffiths" },
    { bookName: "Introduction to Computer Science in Python", authorName: "Robert Sedgewick and Kevin Wayne" },
    { bookName: "Python Programming: An Introduction to Computer Science", authorName: "John Zelle" },
    { bookName: "Learning to Program Using Python", authorName: "Cay Horstmann" },
    { bookName: "Python for Data Science", authorName: "Jake VanderPlas" },
    { bookName: "Python Machine Learning", authorName: "Sebastian Raschka" },
    { bookName: "Deep Learning with Python", authorName: "Francois Chollet" },
    { bookName: "Natural Language Processing with Python", authorName: "Steven Bird, Ewan Klein, and Edward Loper" },
    { bookName: "Automate the Boring Stuff with Python", authorName: "Al Sweigart" },
    { bookName: "Invent Your Own Computer Games with Python", authorName: "Al Sweigart" },
    { bookName: "Python Crash Course", authorName: "Eric Matthes" },
    { bookName: "Learning Python", authorName: "Mark Lutz" },
    { bookName: "Python for Data Analysis", authorName: "Wes McKinney" },
    { bookName: "Python Data Science Handbook", authorName: "Jake VanderPlas" },
    { bookName: "Hands-On Data Science with Anaconda", authorName: "Peter Wang" },
    { bookName: "Full Stack Development with Python", authorName: "Apress" },
    { bookName: "Python Web Development with Flask", authorName: "Miguel Grinberg" },
    { bookName: "Django By Example", authorName: "Antonio Mele" },
    { bookName: "Python Network Programming", authorName: "M. O. Faruque Sarker and Samer Faour" },
    { bookName: "Introduction to Computer Networks", authorName: "Peter L. Dordal" },
    { bookName: "Computer Networks", authorName: "Andrew S. Tanenbaum and David J. Wetherall" },
    { bookName: "Networking Essentials", authorName: "Keith Barker and Scott Duffy" },
    { bookName: "Cybersecurity 101", authorName: "Mark Stanislav" },
    { bookName: "Hacking Exposed", authorName: "Stuart McClure, Joel Scambray, and George Kurtz" },
    { bookName: "The Hacker's Handbook", authorName: "Hugo Cornwall, Steve Gold, and Ben Laurie" },
    { bookName: "Web Application Security Essentials", authorName: "Ofer Shezaf" },
    { bookName: "Data Science for Business", authorName: "Foster Provost and Tom Fawcett" },
    { bookName: "Big Data: The Missing Manual", authorName: "Tim O'Reilly" },
    { bookName: "Data Mining: Practical Machine Learning Tools and Techniques", authorName: "Ian H. Witten, Eibe Frank, and Mark A. Hall" },
    { bookName: "The Data Warehouse Toolkit", authorName: "Ralph Kimball and Margy Ross" },
    { bookName: "Data Visualization: A Handbook for Data Driven Design", authorName: "Andy Kirk" },
    { bookName: "Python Data Analysis", authorName: "Wes McKinney" },
    { bookName: "R for Data Science", authorName: "Hadley Wickham and Garrett Grolemund" },
    { bookName: "SQL Queries for Mere Mortals", authorName: "John D. Cook" },
    { bookName: "The Art of SQL", authorName: "Stephane Faroult" },
    { bookName: "Learning Java", authorName: "Patrick Niemeyer and Daniel Leuck" },
    { bookName: "Java: The Complete Reference", authorName: "Herbert Schildt" },
];


const famousCodingBooks2 = [

    { bookName: "Java Performance: The Definitive Guide", authorName: "Scott Oaks" },
    { bookName: "Java Concurrency in Practice", authorName: "Brian Goetz and Tim Peierls" },
    { bookName: "Head First Java", authorName: "Kathy Sierra and Bert Bates" },
    { bookName: "Java: A Beginner's Guide", authorName: "Herbert Schildt" },
    { bookName: "Java Programming: An Introduction to Computer Science", authorName: "Walter Savitch" },
    { bookName: "Data Structures and Algorithms in Java", authorName: "Michael T. Goodrich et al." },
    { bookName: "Introduction to Algorithms", authorName: "Thomas H. Cormen" },
    { bookName: "The Algorithm Design Manual", authorName: "Steven S. Skiena" },
    { bookName: "Grokking Algorithms", authorName: "Aditya Bhargava" },
    { bookName: "Algorithms to Live By", authorName: "Brian Christian and Tom Griffiths" },
    { bookName: "Introduction to Computer Science in Java", authorName: "Robert Sedgewick and Kevin Wayne" },
    { bookName: "HTML5: The Missing Manual", authorName: "Matthew MacDonald" },
    { bookName: "CSS Pocket Reference", authorName: "Eric A. Meyer" },
    { bookName: "JavaScript Enlightenment", authorName: "Cody Lindley" },
    { bookName: "Eloquent JavaScript", authorName: "Marijn Haverbeke" },
    { bookName: "JavaScript: The Good Parts", authorName: "Douglas Crockford" },
    { bookName: "Node.js in Action", authorName: "Mike Cantelon, Marc Harter, TJ Holowaychuk, and Nathan Rajlich" },
    { bookName: "Full Stack Development with Python", authorName: "Apress" },
    { bookName: "Python Web Development with Flask", authorName: "Miguel Grinberg" },
    { bookName: "Django By Example", authorName: "Antonio Mele" },
    { bookName: "Python Network Programming", authorName: "M. O. Faruque Sarker and Samer Faour" },
    { bookName: "Introduction to Computer Networks", authorName: "Peter L. Dordal" },
    { bookName: "Computer Networks", authorName: "Andrew S. Tanenbaum and David J. Wetherall" },
    { bookName: "Networking Essentials", authorName: "Keith Barker and Scott Duffy" },
    { bookName: "Cybersecurity 101", authorName: "Mark Stanislav" },
    { bookName: "Hacking Exposed", authorName: "Stuart McClure, Joel Scambray, and George Kurtz" },
    { bookName: "The Hacker's Handbook", authorName: "Hugo Cornwall, Steve Gold, and Ben Laurie" },
    { bookName: "Web Application Security Essentials", authorName: "Ofer Shezaf" },
    { bookName: "Data Science for Business", authorName: "Foster Provost and Tom Fawcett" },
    { bookName: "Big Data: The Missing Manual", authorName: "Tim O'Reilly" },
    { bookName: "Data Mining: Practical Machine Learning Tools and Techniques", authorName: "Ian H. Witten, Eibe Frank, and Mark A. Hall" },
    { bookName: "The Data Warehouse Toolkit", authorName: "Ralph Kimball and Margy Ross" },
    { bookName: "Data Visualization: A Handbook for Data Driven Design", authorName: "Andy Kirk" },
    { bookName: "Python Data Analysis", authorName: "Wes McKinney" },
    { bookName: "R for Data Science", authorName: "Hadley Wickham and Garrett Grolemund" },
    { bookName: "SQL Queries for Mere Mortals", authorName: "John D. Cook" },
    { bookName: "The Art of SQL", authorName: "Stephane Faroult" },
    { bookName: "Learning Python", authorName: "Mark Lutz" },
    { bookName: "Python Crash Course", authorName: "Eric Matthes" },
    { bookName: "Automate the Boring Stuff with Python", authorName: "Al Sweigart" },
    { bookName: "Invent Your Own Computer Games with Python", authorName: "Al Sweigart" },
            
];

const updatedFamousCodingBooks2 = famousCodingBooks2.filter(book2 => 
    !famousCodingBooks1.some(book1 => book1.bookName === book2.bookName)
);

// Print the updated array in the specified format
console.log("const famousCodingBooks2 = [");
updatedFamousCodingBooks2.forEach(book => {
    console.log(`    { bookName: "${book.bookName}", authorName: "${book.authorName}" },`);
});
console.log("];");